services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: uharin
      POSTGRES_PASSWORD: uharin
      POSTGRES_DB: vp_db
    ports:
      - "5432:5432"
    networks:
      - vp_network
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: api
    depends_on:
      - postgres
    networks:
      - vp_network
    ports:
      - "3001:3001"
    environment:
      - PORT=3001  # Set the environment variable for the API port
    volumes:
      - ./backend:/usr/src/app
      - ./backend/sql_imports:/usr/src/app/sql_imports

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - vp_network

networks:
  vp_network:
    driver: bridge

volumes:
  postgres_data: